#!/usr/bin/env bash
# installing nginx on 18.234.106.65

sudo apt -y update
sudo apt-get -y install nginx
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
curl -sL /var/www/html/index.html
sudo service nginx start
