#!/usr/bin/env bash
# installing nginx on web server

sudo apt -y update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Hello world!' > /var/www/html/index.html
sudo service nginx start
