#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
substitute_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$substitute_string/g" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
string_404="listen 80 default_server;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/listen 80 default_server;/$string_404/g" /etc/nginx/sites-enabled/default

sudo service nginx restart
