#!/usr/bin/env bash
# A script that pings an Ip addess passed as argument

# Check if an IP address is passed as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 $1
