#!/usr/bin/env bash
# This script is displaying "BEST SCHOOL" but displaying bad luck on the 4th iteration and good luck on the 8th
counter=1
while [ $counter -le 10 ]
do
	if [ $counter = 4 ]
	then
	echo "bad luck"

	elif [ $counter = 8 ]
	then
	echo "good luck"
	
	else
	echo "Best School"
	fi

	((counter++))
done	
